apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bistrot-tatina-api-data
  namespace: bistrot-tatina
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
